### ISSUE TITLE
Not working with Angular 4

### ISSUE THREAD

**Issue by m0squito** [sguiheux/ng2-codemirror-typescript#1]
I just updated my application to Angular 4 and Angular CLI 1.0.0 and this module is preventing the application from compiling. It appears to be a problem with AOT and static analysis. Is anyone still working on this project?

**Comment by sguiheux** [comment]
Hi,
The original repo  ng2-codemirror is not fixed (https://github.com/chymz/ng2-codemirror). You shoud use it instead of this one.
It works on my project angular 4 + angular-cli 1.0.0

**Comment by m0squito** [comment]
Would you mind sharing your package.json for your project? I am getting warnings:
`npm WARN ng2-codemirror@1.1.1 requires a peer of @angular/core@^2.1.0 but none was installed.
npm WARN ng2-codemirror@1.1.1 requires a peer of @angular/forms@^2.1.0 but none was installed.
npm WARN ng2-codemirror@1.1.1 requires a peer of @angular/common@^2.1.0 but none was installed.`

and the codemirror is not highlighting the syntax, everything is black. I'm not sure where is the problem, it worked fine with angular-cli rc and the last stable angular version before 4.0.0. Did you have to make any changes to migrate to ng-4/cli-1?

Thanks

**Comment by sguiheux** [comment]
Hi,

You're right, the is no color anymore with ng2-codemirror.

I just publish a patch
"ng2-codemirror-typescript": "^1.1.1",

Import module : import {CodemirrorModule} from 'ng2-codemirror-typescript/Codemirror';
Import component if you need it: import {CodemirrorComponent} from 'ng2-codemirror-typescript/Codemirror';

It works.

I will try to fix ng2-codemirror later.

**Comment by m0squito** [comment]
@sguiheux Actually, I use ng2-codemirror and fixed the coloring problem by adding this directly in the component:

`import 'codemirror/mode/javascript/javascript.js';`

This works, although it's not as clean as simply adding the *.js mode script to the CLI config file.

Thanks
