### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by diegogvieira** [sguiheux/ng2-codemirror-typescript#2]
Please, could you improve documentation for example, how to import css, mode from codemirror ?

Thanks.

**Comment by sguiheux** [comment]
Hi, it's not the aim of this lib to import codemirror css.

I import css like all others css from external libs. An example here on a project using angular-cli : https://github.com/ovh/cds/blob/master/ui/.angular-cli.json

**Comment by diegogvieira** [comment]
I was able to import css and modes from codemirror, but I cannot import CodemirrorModule.

Seems my app.module.ts cannot find the Module.

here is my systemjs.config.js:

`
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'Scripts/out',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs',
            'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
            'codemirror': 'npm:codemirror',
            'ng2-codemirror-typescript': 'npm:ng2-codemirror-typescript'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'angular2-in-memory-web-api': {
                main: './index.js',
                defaultExtension: 'js'
            }
            // ,
            // 'codemirror': {
            //     main: '../../node_modules/codemirror/lib/codemirror',

            //     defaultExtension: 'js'
            // },
            // 'ng2-codemirror-typescript': {
            //     main: '../../node_modules/ng2-codemirror-typescript/Codemirror',
            //     defaultExtension: 'ts'
            // }
        }
    });
})(this);
`
